# Generated by Django 5.1.3 on 2024-12-15 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='img',
            new_name='image',
        ),
    ]
