# Generated by Django 5.1.3 on 2024-12-14 02:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0002_fooditem"),
    ]

    operations = [
        migrations.AddField(
            model_name="fooditem",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="fooditem",
            name="category",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="fooditem",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="fooditem",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
