# Generated by Django 5.1.3 on 2024-12-14 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0003_fooditem_created_on_alter_fooditem_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fooditem",
            name="category",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="fooditem",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
